# <span style="color:green;">NumPy 03</span>

<span style="color:red;">Creating Sequence</span>
<span style='display:none;'>Copyright All Rights Reserved Ramin Saljoughinejad</span>

In [1]:
import numpy as np

In [2]:
a = np.arange(0,10,1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
b = np.arange(0,10,3)
print(b)

[0 3 6 9]


In [4]:
c = np.arange(7)
print(c)

[0 1 2 3 4 5 6]


In [5]:
d = np.linspace(0,20,6)
print(d)

[ 0.  4.  8. 12. 16. 20.]
